### ISSUE TITLE
ch3_mq_cpmg intensity fitting +/- smallflg

### ISSUE THREAD

**Issue by chriswaudby** [gbouvignies/chemex#12]
I've come across some odd behaviour when fitting methyl MQ dispersions (`cpmg/ch3_mq`), which can be reproduced with the example data:

When `smallflg=Y`, individual intensities are reported:
```
[I0, CH3_MQ_CPMG_600MHZ_18C]
I125CD1-QD1 =  1.11806e+00  5.22935e-02
M145CE-QE =  1.12572e+00  5.23088e-02
M71CE-QE =  1.11097e+00  5.16291e-02

[I0, CH3_MQ_CPMG_800MHZ_18C]
I125CD1-QD1 =  1.12530e+00  5.31967e-02
M145CE-QE =  1.13293e+00  5.37368e-02
M71CE-QE =  1.11289e+00  5.26501e-02
```

However, if I change to `smallflg=N`, they appear to be fitted as a global parameter:
```
[I0, CH3_MQ_CPMG_600MHZ_18C]
I125CD1-QD1 =  1.20760e+00  2.44130e-01
M145CE-QE =  1.20760e+00  2.44054e-01
M71CE-QE =  1.20760e+00  2.44057e-01

[I0, CH3_MQ_CPMG_800MHZ_18C]
I125CD1-QD1 =  1.20760e+00  2.44248e-01
M145CE-QE =  1.20760e+00  2.44286e-01
M71CE-QE =  1.20760e+00  2.44256e-01
```

Any idea what's going on?

Cheers,

Chris

**Comment by viochemist** [comment]
Hello,

Thanks for posting the questions. We've looked into the code and find that the smallflg = N is correct. Basically, in this configuration, the calculation for the reference plane does nothing, so that I0 = 1.0 / (1.0 - pb) +- noise. If the noise is small enough then I0 should be the same for all residues. When smallflg = Y, then the zeta - 180 - zeta element is simulated in the code and I0 will vary not only by pb but also the amount of transverse relaxation that occurs during that period, leading to different values for each residue.

It should be noted that in the paper it is recommended that the sequence always be recorded with the smallflg = Y, so do check to see how your data was recorded and set the flag accordingly.

While investigating the issue, we discovered a small bug in the smallflg = Y calculation, which I have pushed to the development branch. The effect on the fitting should be minimal, but please let us know if you see any dramatic differences from previous results.

Thanks
