### ISSUE TITLE
[Bug] File path automatically read and written as lowercase, which causes example files to unexpectedly terminate.

### ISSUE THREAD

**Issue by chemlzh** [gbouvignies/ChemEx#175]
Anaconda version: 2023.09
ChemEx version: 2022.3.6

**Error description:**

I have downloaded your [1H CEST experiment example](https://github.com/gbouvignies/chemex/tree/master/examples/Experiments/CEST_1HN_IP_AP), and tried to run using the script the example file provided. However, it throw out the error saying that input file was not found. I have checked the data, and the only difference is that the data file from your example has uppercase letters, while the file paths that ChemEx uses are all lowercases. I don't know if the I/O part of ChemEx has done wrongly, so I upload this issue. Hopefully you could fix it ASAP.

Thanks!

**Picture attached:**

![File path error](https://github.com/gbouvignies/ChemEx/assets/32123043/a3a2cd8c-96aa-40af-97a8-5c1a9fa8ad5a)

**Comment by gbouvignies** [comment]
Thank you for identifying this bug. The fix has been implemented in the main branch and a new version will be released shortly. Upon release, please check if the issue is resolved on your system. My testing capabilities are constrained by MacOS's case-insensitive file system. I'll close this issue now, but feel free to reopen it if the problem persists.
