### ISSUE TITLE
Report method step & cluster chi2 values 

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/ChemEx#29]
I for one would find it useful if the step-wise chi2 and reduced chi2 values (at a minimum) would be reported in the chi2.fit file. For instance, a method like this for 5 residues of n_cw cpmg:

```
"method.cfg"

[step 1]
kex = fix
pb = fix
dw = fix
I0 = fit
r_nxy = fit

[step 2]
dw = fit

[step 3]
kex = fit
pb = fit
dw = fit
````

with the result:

```
"chi2.fit"

### step 1 ###
#-- cluster commonalities [[ie. what determines the clustering]]
# 1     01N,600.0
# 2     02N,600.0
# 3     03N,600.0
# 4     04N,600.0
# 5     05N,600.0
# 6     01N,800.0
# 7     02N,800.0
# 8     03N,800.0
# 9     04N,800.0
# 10    05N,800.0
# -- fitting parameters
# r_nxy
# I0
#   cluster          chi2           ndata            npar           rchi2      
1	3.3715E+01	20	2	1.8731E+00
2	2.7464E+01	20	2	1.5258E+00
3	3.2147E+01	20	2	1.7859E+00
4	3.4446E+01	20	2	1.9137E+00
5	2.9090E+01	20	2	1.6161E+00
6	3.0484E+01	22	2	1.5242E+00
7	3.1531E+01	22	2	1.5766E+00
8	3.5835E+01	22	2	1.7918E+00
9	3.9198E+01	22	2	1.9599E+00
10	3.2636E+01	22	2	1.6318E+00
all	3.2655E+02	210	20	1.7187E+00
				
### step 2 ###
#-- cluster commonalities 
# 1     01N,dw
# 2     02N,dw
# 3     03N,dw
# 4     04N,dw
# 5     05N,dw
# -- fitting parameters
# r_nxy,600.0
# r_nxy,800.0
# I0,600.0
# I0,800.0
# dw
#   cluster          chi2           ndata            npar           rchi2      
1	3.8867E+01	42	5	1.0505E+00
2	3.8315E+01	42	5	1.0356E+00
3	4.3899E+01	42	5	1.1864E+00
4	4.1400E+01	42	5	1.1189E+00
5	4.2583E+01	42	5	1.1509E+00
all	2.0506E+02	210	25	1.1085E+00

### step 3 ###
#-- cluster commonalities 
# 1     kex,pb
[[ skip fitting parameters if only 1 cluster]]
#   cluster          chi2           ndata            npar           rchi2      
1	2.4274E+02	210	27	1.3265E+00
```

I've of course gone a little crazy with the potential example, but hopefully the idea comes across and someone can think of an even better way to organize the results.

If you're asking "why?", largely it's to be able to compare individual vs. global fitting without having to run everthing separately, then writing scripts to add and compare all of the chi2 values. If there's a way to internally compare chi2 values (step1 vs step2 vs step 3, or cluster 1 vs all), it would be even better!

Just food for thought, and to give myself a reminder.

**Comment by reneeotten** [comment]
I like that idea Alex! It should be fairly easy to do so, since all the statistics are already calculated/collected after the fit is performed (i.e., in `result = minimizer.minimize(method=fitmethod, params=c_params)`). We can grab the information from `result` and write that to an output file.

I guess we could also remove some of statistics-related stuff from `datasets.py` in the process and re-organize this into `fitting.py`.

**Comment by gbouvignies** [comment]
I am totally on board with this. Should not be too much work... 

Actually, I am almost tempted to create an `output` directory with all the usual files (including the plots) for each step of the method. The `chi2.fit` file could then be extended to include cluster-specific values in addition to the global chi2 value.

In order to compare "individual" vs. "global" fit easily, wouldn't it be handy to create an exchange model in which all "global" exchange parameters are site-specific?

**Comment by gbouvignies** [comment]
All implemented in the last version.
