### ISSUE TITLE
bootstrap and Monte-Carlo not working

### ISSUE THREAD

**Issue by reneeotten** [gbouvignies/ChemEx#34]
In the `feature/from_point_to_profile` branch, the options `--mc` and `--bs` do now work due to an issue with `copy.deepcopy`. 

I think the solution is to add `import copy` and define a `__deepcopy__` method in all the `experiments/{cest/cpmg}/profiles/*.py` files:
```
    def __deepcopy__(self, memo):
        return Profile(copy.deepcopy(self.profile_name , memo),
                               copy.deepcopy(self.measurements, memo),
                               copy.deepcopy(self.exp_details, memo))
```

and then add under the `__init__` in `{cest/cpmg}_profile.py the following lines:

```
        self.measurements = measurements
        self.exp_details = exp_details
```

This will just return a newly initialized Profile identical to the original one. The only issue here would be if methods change the attributes of the Profile class after its initialization. As far as I can tell this only happens when using the `filter_points` method and, therefore, potentially only for CEST data. Anyway, I think we can easily avoid trouble here and just do

```
                for profile in data_index:
                    profile.filter_points(params)
                data_index.ndata = sum([len(profile.val) for profile in data_index])
```

after making a new data set, `data_index`, in `chemex.py` before we fit the data again the the Monte-Carlo or bootstrap.

I will put this into a PR after some of the other stuff is merged to avoid too many conflicts. In my *limited* testing this seems to work all as intended, but it certainly needs some more verification. If you see any possible issues with this approach, or know a better/other way of solving it, please let me know!

**Comment by gbouvignies** [comment]
I had it to work by simply using `copy.copy` instead of `copy.deepcopy`. I could not see any side effect. Do you see anything wrong with this?

However, for some reason I don't fully understand, I had to modify the `calculate_scale` method to take into account the case where all values in `cal` are 0.0.

        def calculate_scale(self, cal):
            """Calculate the scaling factor."""
            norm = sum((cal / self.err)**2)
    
            if norm:
                scale = (sum(cal * self.val / self.err**2) / norm)
            else:
                scale = 0.0
    
            return scale

**Comment by reneeotten** [comment]
the reason I was in favor of doing a `deepcopy` is not to alter the raw, input data. 

However, it looks like that this anyway doesn't happen if you use the bootstrap (for reasons I don't fully understand). 
```
original data = <chemex.datasets.DataSet object at 0x107753d68>
original first profile = <chemex.experiments.cest.profiles.ip.Profile object at 0x10c18d5c0>
data_index (bootstrap) = <chemex.datasets.DataSet object at 0x10c230ef0>
data_index first profile (bootstrap) = <chemex.experiments.cest.profiles.ip.Profile object at 0x10c2ab3c8>
```
the references for `DataSet` and `Profile` are different for the original `data` and the `data_index` generated for the boostrap. So that's all good. 

One does actually change the input data when doing the Monte-Carlo:
```
original data = <chemex.datasets.DataSet object at 0x1067cfd68>
original first profile = <chemex.experiments.cest.profiles.ip.Profile object at 0x10b2b3fd0>
data_index (Monte-Carlo) = <chemex.datasets.DataSet object at 0x10b5d6d68>
data_index first profile (Monte-Carlo) = <chemex.experiments.cest.profiles.ip.Profile object at 0x10b2b3fd0>
```
here the reference for `Profile` is the same in the original `data` and `data_index`.

However, since we generate the synthetic dataset from the best-fit parameters + random noise it doesn't really matter I guess.

So I think you are correct that replacing `deepcopy` with `copy` in `data_mc = copy.deepcopy(data)` in `chemex.py` and `profile = copy.deepcopy(self)` in `experiments/{cest/cpmg}/{cest/cpmg}_profile.py` should be sufficient.

It will need a fix for `params_mc = copy.deepcopy(result.params)` in `chemex.py` that I introduced when using the MinimizerResult. I think it should become:
```
            for index in range(1, nmb + 1):
                if args.bs:
                    data_index = make_bootstrap_dataset(data)
                    params_mc = copy.deepcopy(params)
                else:
                    params_mc = copy.deepcopy(result.params)
                    data_index = make_montecarlo_dataset(data, result.params)

                output_dir_ = os.path.join(output_dir, formatter_output_dir.format(index))       
``` 

Do you already have this finished or do you want me to put this into a PR?

**Comment by reneeotten** [comment]
or, alternatively... we could always do an initial fit with the original data before doing a bootstrap as well and change the code accordingly.

**Comment by reneeotten** [comment]
thanks, looks good to me!

**Comment by reneeotten** [comment]
sorry for trying to re-open this issue.... I think there is one more thing to discuss about the bootrapping. 

The way it works now, by randomly selecting data points out of the original data set I think works well if you want to bootstrap individual residues. The only thing I am a bit confused about is that we're not really throwing out data points but randomly selecting points up to the same number of original data points (which will give rise to duplication of data points). I am not completely sure whether that could cause issues for the fitting or for the statistics.

However, if you would do a global fit and want to get bootstraps there - I think one would then do bootstrapping on a residue basis instead of a Profile basis or...?

**Comment by chriswaudby** [comment]
Hi,

Just to pitch in here (sorry I haven’t been following the discussion of code!)… I can recommend ‘An introduction to the bootstrap’ by Efron and Tibshirani if you want to check out more of the theory, I found it helpful when I was writing the bootstrap analysis for TITAN. Chapter 9 (p113) is maybe particularly relevant, where there’s a discussion of two bootstrapping approaches:

1) bootstrapping pairs (which I think is what you’re doing here) - randomly resampling data points with replacement
2) bootstrapping residuals (what I did in TITAN) - taking the predicted fit, and randomly resampling the residuals (with replacement) and adding them back to make a new dataset

Efron makes the point that pair resampling is generally good because you don’t make any assumptions about the model being a good fit, whereas residual resampling can end up being too conservative if the model is wrong. So that’s good news for chemex! My only concern with this approach might be that not all data points in a CEST profile have the same information content, so there’s a risk of generating datasets without any dips (you can easily show the probability of an individual point being omitted is 1/e=0.367 for large N)…

FYI - if there’s correlation expected between data points then (1) runs into particular trouble, but (2) can be adapted by resampling blocks of residuals, which is why I used this approach for TITAN. Probably not relevant here though as I can’t see any reason to expect such correlations.

Chris

**Comment by gbouvignies** [comment]
The information content is indeed not the same depending on the data points – CEST baseline points vs. points defining CEST dips or points from the reference planes. I don't think, there's much to do regarding the points of the dips. However, chemex resamples "reference" and "non-reference" points independently, so that there's always the same number of reference points picked in the new sample. This is necessary if one doesn't want to end up with a profile lacking any reference point, which would be an issue to estimate `r1` (CEST) or `r2` (CPMG).

As Renee noticed, the resampling is done at the profile level. This is because some parameters can depend on one specific profile only. As bootstrap strategy consists in producing samples with the same number of points as the original sample, I thought it might be better to enforce this constraint at the profile level.

There might be better ways of doing it... I am open for suggestions.
