### ISSUE TITLE
CEST processing: two states with identical unbound chemical shifts, but different bound state chemical shifts

### ISSUE THREAD

**Issue by FrederikTheisen** [gbouvignies/ChemEx#64]
Hi

I'm trying to analyze some CEST data where I have two different unbound states in very slow exchange (basically zero exchange) with the same chemical shift in a 15N-HSQC. Upon binding, the two states will differ and thus a single peak shows three-state behavior, even though it is actually 2 x two-state behavior. I know the Keq of the two unbound states.

While the data fits a three-state model, I'm not sure the output values are meaningful since the ground state effectively contains two different molecules.

What I need is a four-state model, with two binding events (A->B and C->D) and potentially two very slow isomerization event (A->C and B->D). But since my observed peak contains both A and C state, I need to detect saturation of both the A state and the C state.

I've implemented this by duplicating the 15N-CEST experiment and changing the detect function to return "[iz_a] + [iz_c]" which appears to work.

My question is if this is a reasonable thing to do?

Thanks.
Frederik

**Comment by viochemist** [comment]
Hi,

From what I'm understanding, you have two independent exchange processes going on, but they share a common state. I believe this would be best described by an off-pathway 3-state where B <-> A <-> C, and you would set B <-> C rates to 0. 

In the scenario where you have two chemically identical states A that slowly exchange, I don't think there's any way to experimentally see that. Perhaps if you run an EXSY experiment, you may see a cross-peak between B and C states, if they're populated enough to even see them, but presumably they are not which is why you are using CEST. 

As for your 4-state alternative, I would need to run some simulations, but I think that just boils down to the 3-state mentioned above. I'm not sure the data can accurately capture differences between the two options.

Those are my 2 cents anyways.

**Comment by FrederikTheisen** [comment]
Hi thanks for your response.

To clarify, this is proline cis/trans isomerization, with a 30% cis population and thus very visible and assignable in NMR.
The model is only speculation, and I'm currently producing a mutant (removing the proline) which will result in only one ground state.

The shared peak position is thus not a common state, but contains what is effectively two different molecules. There is an equilibrium constant between the two molecules, but the Kex is << 1. Thus I have two indenpendent exchange processes that share an exact peak position. I know the equilibrium constant between the two ground states and thus also the intensity ratio between the two.

If I modeled this using 3 states, state A would contain a mix of two different molecules.
